#ifndef STANDARDDATASTRUCTURE_H_INCLUDED
#define STANDARDDATASTRUCTURE_H_INCLUDED

#define TEMP_LEN 10
#define RETURN_INFO_LEN 10
#define BOOK_NAME_LEN 45
#define PUBLISHER_LEN 25
#define AUTHOR_LEN 25
#define PUBLISH_DATE_LEN 5
#define BORROW_TIME_LEN 11
#define RECENT_BORROWED_ID_LEN 10
#define BOOKS_BORROWED_LEN 5
#define PASSWORD_LEN 10
#define PEOPLE_NAME_LEN 20
#define FALSE_DISTANCE -1

#endif // STANDARDDATASTRUCTURE_H_INCLUDED
